version: '3'
services:
    bff:
        build: ./bff
        ports:
            - 9020:9020
        depends_on:
            - evaluation
            - recommend
    evaluation:
        build: ./evaluation
        ports:
            - 9030:9030
        depends_on:
            - 'db'
    recommend:
        build: ./recommend
        ports:
            - 9040:9040
        depends_on:
            - 'db'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db
            - PMA_USER=root
            - PMA_PASSWORD=miraiketai2020_admin
        ports:
            - 8080:80
        depends_on:
            - 'db'
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'miraiketai2020_admin'
            # MYSQL_DATABASE: 'michishirube'
            MYSQL_USER: 'miraiketai2020'
            MYSQL_PASSWORD: 'miraiketai2020'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306