version: '3'
services:
    bff:
        build: ./bff
        ports:
            - 9020:9020
        depends_on:
            - 'evaluation'
            - 'recommend'
    evaluation:
        build: ./evaluation
        ports:
            - 9030:9030
        depends_on:
            - 'db'
    recommend:
        build: ./recommend
        ports:
            - 9040:9040
        depends_on:
            - 'db'
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'miraiketai2020_admin'
            MYSQL_DATABASE: 'michishirube'
            MYSQL_USER: 'miraiketai2020'
            MYSQL_PASSWORD: 'miraiketai2020'